name = "StochasticWeatherGenerators"
uuid = "3eadb0b9-5057-49d2-9b8f-52a8c334ebf6"
authors = ["David MÃ©tivier <david.metivier@inrae.fr>"]
version = "1.0.5-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Copulas = "ae264745-0b69-425e-9d9d-cf662c5eec93"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
Impute = "f7bf1975-0170-51b9-8c5f-a992d46b9575"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RollingFunctions = "b0e4dd01-7b14-53d8-9b45-175a3e362653"
SmoothPeriodicStatsModels = "3d8e1505-165e-443f-a184-83a230b5a9e5"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"
SmoothPeriodicStatsModels = "1.0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
